### ISSUE TITLE
Why ignore BlueSnap response data?

### ISSUE THREAD

**Issue by pmccarren** [tdanielcox/bluesnap-php#1]
Greetings!

The following two snippets essentially ignore all data return back from BlueSnap, other than `id`:
https://github.com/tdanielcox/bluesnap-php/blob/bd86095e943d97bf857ff519aa391efb9d206d90/src/Bluesnap/Adapter.php#L67
https://github.com/tdanielcox/bluesnap-php/blob/bd86095e943d97bf857ff519aa391efb9d206d90/src/Bluesnap/Api.php#L70-L75
I am wondering the utility of this and why it is necessary?

Thank you!

**Comment by pmccarren** [comment]
I'm curious if this would break anything that you're aware of? https://github.com/ventepos/bluesnap-php/commit/50ab732e01406e4f380417b53e4196e4d9f63aae

**Comment by tdanielcox** [comment]
In my particular use case, I didn't need the response data I just needed the ID. 

If I remember correctly, bluesnap does not include a response body in many of their api calls. Sometimes they just return the ID of the posted model in the body, and sometimes they return no response body and return the ID only in the 'Location' header, which the code that you asked about handles. 

For instance in the [CardTransaction](https://github.com/tdanielcox/bluesnap-php/blob/master/src/Bluesnap/CardTransaction.php) class, you can see that 'id_in_header' is set to false because the ID of the posted transaction gets returned in the body. Alternatively, in the [Vendor](https://github.com/tdanielcox/bluesnap-php/blob/master/src/Bluesnap/Vendor.php) class, 'id_in_header' is not specified (defaults to true) so this means that the ID of the posted vendor is returned in the Location header, so it needs to be pulled from there.

The code that you removed will break many of the endpoints, so I would recommend keeping it and just merging the response body to the array if you need the body contents as well.

You can achieve that by replacing line 76 of the Api class with this:

```php
$res = $response->getBody()->getContents();
$res['id'] = (int) $model_id;
return $res;
```

Unfortunately my company decided against using BlueSnap, so I am no longer maintaining this library. Feel free to fork and modify this package to fit your needs. All the endpoints are tested and working as of 6 months ago, however I didn't get the opportunity to write any tests or completely cover all the API endpoints.  Regardless this library solves many of the problems and inconsistencies I ran into while integrating BlueSnap (like the unknown ID location that I mentioned earlier), so it is a good starting point for you to build off of and will hopefully save you some time.

Feel free to ask any questions and I will do my best to answer them.

**Comment by pmccarren** [comment]
Thank you for taking the time to explain the nuances of working with the BlueSnap API. You definitely saved me time.

The first action I tested was creating a VaultedShopper with an encryptedCardNumber, and naturally in that _one instance_, it appears BlueSnap added a response body 😆 . Attempting to get at said body to retrieve the cardLastFourDigits led me to open this issue. After changing the `VaultedShopper@create` method to include `id_in_header => false`, the full body is returned and all is well.

Additionally, I started passing `id_in_header` to the `Api@post` method, making it so the Location header parsing is only done if the id is in the header.

We're currently evaluating BlueSnap and if we commit to them I'm sure I'll be able to help build out tests and such.

Thanks again!
